/**
Helper module for constructing plugin options when we are running in local development mode.
Options are constructed based on data from .chcpenv file. That file is generated by the
cordova-hcp CLI client.
*/
(function() {

  module.exports = {
    load: loadDefault
  };

  /**
   * Construct default options for local development.
   *
   * @param {Object} chcpEnvConfig - data from .chcpenv file
   * @return {Object} generated local development options
   */
  function loadDefault(chcpEnvConfig) {
    if (chcpEnvConfig == null) {
      return null;
    }

    var localDevModeOptions = prepareLocalDevModeOptions(chcpEnvConfig);

    return {
      'config-file': chcpEnvConfig.config_url,
      'local-development': localDevModeOptions
    };
  }

  function prepareLocalDevModeOptions(chcpEnvConfig) {
    return {
      enabled: true
    };
  }

})();
